# Generated by Django 3.2 on 2026-01-25 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True, null=True)),
                ('association', models.CharField(choices=[('None', 'None'), ('YES', 'YES'), ('JCOM', 'JCOM'), ('JCI', 'JCI'), ('Rotary', 'Rotary'), ('Tridisha', 'Tridisha'), ('Builder Association', 'Builder Association')], default='None', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('IT Software', 'IT Software'), ('IT Hardware', 'IT Hardware'), ('AMC Service', 'AMC Service'), ('Website Development', 'Website Development'), ('Mobile App Development', 'Mobile App Development')], max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('priority', models.CharField(default='Normal', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('mom_pdf', models.FileField(blank=True, null=True, upload_to='mom/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='api.client')),
            ],
        ),
    ]
