# Generated by Django 3.2 on 2026-01-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('None', 'None'), ('IT Software', 'IT Software'), ('IT Hardware', 'IT Hardware'), ('Academy', 'Academy'), ('HRMS', 'HRMS'), ('Event Management', 'Event Management'), ('Industrial Solutions', 'Industrial Solutions')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='association',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('YES', 'YES'), ('JCOM', 'JCOM'), ('JCI', 'JCI'), ('Rotary', 'Rotary'), ('THUDITSSIA', 'THUDITSSIA'), ('Builder Association', 'Builder Association')], default='None', max_length=50),
        ),
    ]
